compat_wl18xx: update with R8.4 version
Update the compat_wl18xx directory with the new driver from
R8.4 release (ol_r8.a9.14)

Change-Id: I42991b5c9f85918366b3163f858cd3dead78664b
Signed-off-by: Eyal Reizer <eyalr@ti.com>
Signed-off-by: D. Andrei Măceș <dmaces@nd.edu>

diff --git a/mac80211/compat_wl18xx/Makefile b/mac80211/compat_wl18xx/Makefile
--- a/mac80211/compat_wl18xx/Makefile
+++ b/mac80211/compat_wl18xx/Makefile
@@ -1,263 +1,165 @@
 #
-
-# Copyright (c) 2007-2012 Luis R. Rodriguez <mcgrof@frijolero.org>
+# Makefile for the output source package
 #
-# Permission to use, copy, modify, and/or distribute this software for any
-# purpose with or without fee is hereby granted, provided that the above
-# copyright notice and this permission notice appear in all copies.
-#
-# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
-# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
-# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
-# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
-# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
-# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
-# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-export KMODDIR?=       updates
-KMODDIR_ARG:=   "INSTALL_MOD_DIR=$(KMODDIR)"
+ifeq ($(KERNELRELEASE),)
+
+MAKEFLAGS += --no-print-directory
+SHELL := /bin/bash
+BACKPORT_PWD := $(shell pwd)
+
+KMODDIR ?= updates
 ifneq ($(origin KLIB), undefined)
-KMODPATH_ARG:=  "INSTALL_MOD_PATH=$(KLIB)"
+KMODPATH_ARG := "INSTALL_MOD_PATH=$(KLIB)"
+ROOTFS_DIR := $(KLIB)
 else
-export KLIB:=          /lib/modules/$(shell uname -r)
+KLIB := /lib/modules/$(shell uname -r)/
+KMODPATH_ARG :=
+ROOTFS_DIR :=
 endif
-export KLIB_BUILD ?=	$(KLIB)/build
-export MAKE
+KLIB_BUILD ?= $(KLIB)/build/
+KERNEL_CONFIG := $(KLIB_BUILD)/.config
+KERNEL_MAKEFILE := $(KLIB_BUILD)/Makefile
+CONFIG_MD5 := $(shell md5sum $(KERNEL_CONFIG) 2>/dev/null | sed 's/\s.*//')
 
-DESTDIR?=
+export KLIB KLIB_BUILD BACKPORT_PWD KMODDIR KMODPATH_ARG ROOTFS_DIR
 
-ifneq ($(KERNELRELEASE),)
+# disable built-in rules for this file
+.SUFFIXES:
 
--include $(COMPAT_CONFIG)
-include $(COMPAT_CONFIG_CW)
+.PHONY: default
+default:
+	@$(MAKE) modules
 
-NOSTDINC_FLAGS := \
-	-I$(M)/include/ \
-	-I$(M)/include/uapi \
-	-I$(M)/include/drm \
-	-include $(M)/include/linux/compat-2.6.h \
-	$(CFLAGS)
+.PHONY: mrproper
+mrproper:
+	@test -f .config && $(MAKE) clean || true
+	@rm -f .config
+	@rm -f .kernel_config_md5 Kconfig.versions Kconfig.kernel
+	@rm -f backport-include/backport/autoconf.h
 
-obj-y := compat/
+.DEFAULT:
+	@set -e ; test -f .local-symbols || (						\
+	echo "/--------------"								;\
+	echo "| You shouldn't run make in the backports tree, but only in"		;\
+	echo "| the generated output. This here is only the skeleton code"		;\
+	echo "| copied into the output directory. To use the backport system"		;\
+	echo "| from scratch, go into the top-level directory and run"			;\
+	echo "|	./gentree.py /path/to/linux-next/ /tmp/output"				;\
+	echo "| and then make menuconfig/... in the output directory. See"		;\
+	echo "|	./gentree.py --help"							;\
+	echo "| for more options."							;\
+	echo "\\--"									;\
+	false)
+	@set -e ; test -f $(KERNEL_CONFIG) || (						\
+	echo "/--------------"								;\
+	echo "| Your kernel headers are incomplete/not installed."			;\
+	echo "| Please install kernel headers, including a .config"			;\
+	echo "| file or use the KLIB/KLIB_BUILD make variables to"			;\
+	echo "| set the kernel to build against, e.g."					;\
+	echo "|   make KLIB=/lib/modules/3.1.7/"					;\
+	echo "| to compile/install for the installed kernel 3.1.7"			;\
+	echo "| (that isn't currently running.)"					;\
+	echo "\\--"									;\
+	false)
+	@set -e ; if [ "$$(cat .kernel_config_md5 2>/dev/null)" != "$(CONFIG_MD5)" ]	;\
+	then 										\
+		echo -n "Generating local configuration database from kernel ..."	;\
+		grep -v -f .local-symbols $(KERNEL_CONFIG) | grep = | (			\
+			while read l ; do						\
+				if [ "$${l:0:7}" != "CONFIG_" ] ; then			\
+					continue					;\
+				fi							;\
+				l=$${l:7}						;\
+				n=$${l%%=*}						;\
+				v=$${l#*=}						;\
+				if [ "$$v" = "m" ] ; then				\
+					echo config $$n					;\
+					echo '    tristate' 				;\
+				elif [ "$$v" = "y" ] ; then				\
+					echo config $$n					;\
+					echo '    bool'					;\
+				else							\
+					continue					;\
+				fi							;\
+				echo "    default $$v"					;\
+				echo ""							;\
+			done								\
+		) > Kconfig.kernel							;\
+		kver=$$($(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelversion |	\
+			sed 's/^\(\(3\|2\.6\)\.[0-9]\+\).*/\1/;t;d')			;\
+		test "$$kver" != "" || echo "Kernel version parse failed!"		;\
+		test "$$kver" != ""							;\
+		kvers="$$(seq 14 39 | sed 's/^/2.6./')"					;\
+		kvers="$$kvers $$(seq 0 99 | sed 's/^/3./')"				;\
+		print=0									;\
+		for v in $$kvers ; do							\
+			if [ "$$print" = "1" ] ; then					\
+				echo config BACKPORT_KERNEL_$$(echo $$v | tr . _)	;\
+				echo "    def_bool y"					;\
+			fi								;\
+			if [ "$$v" = "$$kver" ] ; then print=1 ; fi			;\
+		done > Kconfig.versions							;\
+		# RHEL as well, sadly we need to grep for it				;\
+		RHEL_MAJOR=$$(grep '^RHEL_MAJOR' $(KERNEL_MAKEFILE) | 			\
+					sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
+		RHEL_MINOR=$$(grep '^RHEL_MINOR' $(KERNEL_MAKEFILE) | 			\
+					sed 's/.*=\s*\([0-9]*\)/\1/;t;d')		;\
+		for v in $$(seq 0 $$RHEL_MINOR) ; do 					\
+			echo config BACKPORT_RHEL_KERNEL_$${RHEL_MAJOR}_$$v		;\
+			echo "    def_bool y"						;\
+		done >> Kconfig.versions						;\
+		echo " done."								;\
+	fi										;\
+	echo "$(CONFIG_MD5)" > .kernel_config_md5
+	@$(MAKE) -f Makefile.real "$@"
 
-#obj-$(CONFIG_COMPAT_RFKILL) += net/rfkill/
+.PHONY: defconfig-help
+defconfig-help:
+	@echo "Driver or subsystem configuration targets:"
+	@set -e						;\
+		bk_configs="$$(ls defconfigs/*)" 	;\
+		for cfg in $$bk_configs; do		\
+			echo "  defconfig-$${cfg##defconfigs/}"	;\
+		done
+	@echo ""
 
-#obj-$(CONFIG_COMPAT_MEDIA_MODULES) += drivers/media/v4l2-core/
-#obj-$(CONFIG_COMPAT_MEDIA_MODULES) += drivers/media/usb/uvc/
-
-ifeq ($(BT),)
-obj-$(CONFIG_COMPAT_WIRELESS) += net/wireless/ net/mac80211/
-obj-$(CONFIG_COMPAT_WIRELESS_MODULES) += drivers/net/wireless/
-
-
-
-
-ifeq ($(CONFIG_STAGING_EXCLUDE_BUILD),)
-endif
-
-endif
-
-
+.PHONY: help
+help: defconfig-help
+	@echo "Cleaning targets:"
+	@echo "  clean           - Remove most generated files but keep the config and"
+	@echo "                    enough build support to build external modules"
+	@echo "  mrproper        - Remove all generated files + config + various backup files"
+	@echo ""
+	@echo "Driver configuration help:"
+	@echo "  defconfig-help  - List all prearranged defconfig-targets we have"
+	@echo "                    designed for you. You can use this to find"
+	@echo "                    driver specific configs in case all you really"
+	@echo "                    need is to just compile one or a small group "
+	@echo "                    of drivers."
+	@echo ""
+	@echo "Configuration targets:"
+	@echo "  menuconfig      - Update current config utilising a menu based program"
+	@echo "  oldconfig       - Update current config utilising a provided .config as base"
+	@echo "  oldaskconfig    - ??"
+	@echo "  silentoldconfig - Same as oldconfig, but quietly, additionally update deps"
+	@echo "  allnoconfig     - New config where all options are answered with no"
+	@echo "  allyesconfig    - New config where all options are accepted with yes"
+	@echo "  allmodconfig    - New config selecting modules when possible"
+	@echo "  alldefconfig    - New config with all symbols set to default"
+	@echo "  randconfig      - New config with random answer to all options"
+	@echo "  listnewconfig   - List new options"
+	@echo "  olddefconfig    - Same as silentoldconfig but sets new symbols to their default value"
+	@echo ""
+	@echo "Other generic targets:"
+	@echo "  all             - Build all targets marked with [*]"
+	@echo "* modules         - Build all modules"
+	@echo ""
+	@echo "Architecture specific targets:"
+	@echo "  install         - Install modules"
+	@echo "  uninstall       - Uninstall modules"
+	@echo ""
+	@echo "Execute "make" or "make all" to build all targets marked with [*]"
 else
-
-export PWD :=	$(shell pwd)
-
-# The build will fail if there is any space in PWD.
-ifneq (,$(findstring  $() ,$(PWD)))
-$(error "The path to this compat-drivers directory has spaces in it." \
-	"Please put it somewhere where there is no space")
+include $(BACKPORT_PWD)/Makefile.kernel
 endif
-
-# For C code
-export CFLAGS += \
-        -DCOMPAT_BASE="\"$(shell cat $(PWD)/.compat_base)\"" \
-        -DCOMPAT_BASE_TREE="\"$(shell cat $(PWD)/.compat_base_tree)\"" \
-        -DCOMPAT_BASE_TREE_VERSION="\"$(shell cat $(PWD)/.compat_base_tree_version)\"" \
-        -DCOMPAT_PROJECT="\"compat-drivers\"" \
-        -DCOMPAT_VERSION="\"$(shell cat $(PWD)/.compat_version)\""
-
-# These exported as they are used by the scripts
-# to check config and compat autoconf
-export COMPAT_CONFIG_CW=$(PWD)/config.mk
-export COMPAT_CONFIG=$(PWD)/.config
-export CONFIG_CHECK=$(PWD)/.config.mk_md5sum.txt
-export COMPAT_AUTOCONF=include/linux/compat_autoconf.h
-export CREL=$(shell cat $(PWD)/.compat_version)
-export CREL_PRE:=.compat_autoconf_
-export CREL_CHECK:=$(PWD)/$(CREL_PRE)$(CREL)
-
-all: modules
-
-$(COMPAT_CONFIG): ;
-
-menuconfig:
-	@echo "Not yet supported, still under development"
-	@echo "If you want to hack on this start testing with:"
-	@echo "    make -f scripts/kconfig/Makefile menuconfig "
-	@exit 1
-	make -f scripts/kconfig/Makefile menuconfig
-
-modules: $(CREL_CHECK)
-	+@./scripts/check_config.sh
-	$(MAKE) -C $(KLIB_BUILD) M=$(PWD) modules
-	@touch $@
-
-bt: $(CREL_CHECK)
-	+@./scripts/check_config.sh
-	$(MAKE) -C $(KLIB_BUILD) M=$(PWD) BT=TRUE modules
-	@touch $@
-
-# We use a CREL_CHECK variable which will depend on the environment used to
-# build. If the environment requirements change it forces a reconfiguration
-# check.  This means we force a new reconfiguration check if a the user gets a
-# new updates of compat-drivers or when the user updates the $(COMPAT_CONFIG)
-# file.
-# XXX: add kernel target to the CREL_CHECK mix, this would ensure we also
-# reconfigure and build again fresh if we detect a new target kernel is
-# being used.
-$(CREL_CHECK):
-	@# Force to regenerate compat autoconf
-	+@./compat/scripts/gen-compat-config.sh > $(COMPAT_CONFIG)
-	@rm -f $(CONFIG_CHECK)
-	+@./scripts/check_config.sh
-	@md5sum $(COMPAT_CONFIG_CW) > $(CONFIG_CHECK)
-	@touch $@
-
-btinstall: btuninstall bt-install-modules
-
-bt-install-modules: bt
-	$(MAKE) -C $(KLIB_BUILD) M=$(PWD) $(KMODDIR_ARG) $(KMODPATH_ARG) BT=TRUE \
-		modules_install
-	@/sbin/depmod -ae
-	@echo
-	@echo Now run:
-	@echo
-	@echo sudo make btunload:
-	@echo
-	@echo And then load the needed bluetooth modules. If unsure reboot.
-	@echo
-
-btuninstall:
-	@# New location, matches upstream
-	@rm -rf $(KLIB)/$(KMODDIR)/net/bluetooth/
-	@rm -rf $(KLIB)/$(KMODDIR)/drivers/bluetooth/
-	@# Lets only remove the stuff we are sure we are providing
-	@# on the misc directory.
-	@/sbin/depmod -ae
-	@echo
-
-btclean:
-	$(MAKE) -C /lib/modules/$(shell uname -r)/build M=$(PWD) BT=TRUE clean
-	@rm -f $(CREL_PRE)*
-
-install: uninstall install-modules install-scripts
-
-install-modules: modules
-	$(MAKE) -C $(KLIB_BUILD) M=$(PWD) $(KMODDIR_ARG) $(KMODPATH_ARG) \
-		modules_install
-	@./scripts/blacklist.sh $(KLIB)/ $(KLIB)/$(KMODDIR)
-	@/sbin/depmod -a
-
-install-scripts:
-	@# All the scripts we can use
-	@mkdir -p $(DESTDIR)/usr/lib/compat-drivers/
-	@install scripts/modlib.sh	$(DESTDIR)/usr/lib/compat-drivers/
-	@install scripts/git-paranoia	$(DESTDIR)/usr/sbin/
-	@install scripts/madwifi-unload	$(DESTDIR)/usr/sbin/
-	@# This is to allow switching between drivers without blacklisting
-	@install scripts/athenable	$(DESTDIR)/usr/sbin/
-	@install scripts/b43enable	$(DESTDIR)/usr/sbin/
-	@install scripts/iwl-enable	$(DESTDIR)/usr/sbin/
-	@install scripts/athload	$(DESTDIR)/usr/sbin/
-	@install scripts/b43load	$(DESTDIR)/usr/sbin/
-	@install scripts/iwl-load	$(DESTDIR)/usr/sbin/
-	@if [ $(shell modinfo ath_pci > /dev/null 2>&1 && echo 1) ]; then \
-		echo -n "Note: madwifi detected, we're going to disable it. "  ;\
-		echo "If you would like to enable it later you can run:"  ;\
-		echo "    sudo athenable madwifi"  ;\
-		echo ;\
-		echo Running athenable ath5k...;\
-		$(DESTDIR)/usr/sbin/athenable ath5k ;\
-	fi
-	@if [ $(shell modinfo iwl4965 > /dev/null 2>&1 && echo 1) ]; then \
-		echo ;\
-		echo -n "Note: iwl4965 detected, we're going to disable it. "  ;\
-		echo "If you would like to enable it later you can run:"  ;\
-		echo "    sudo iwl-load iwl4965"  ;\
-		echo ;\
-		echo Running iwl-enable iwlagn...;\
-		$(DESTDIR)/usr/sbin/iwl-enable iwlagn ;\
-	fi
-	@if [ $(shell modinfo iwlagn > /dev/null 2>&1 && echo 1) ] \
-	 && [ $(shell modinfo iwlwifi > /dev/null 2>&1 && echo 1) ]; then \
-		echo ;\
-		echo -n "Note: iwlagn detected, we're going to disable it. " ;\
-		echo "If you would like to enable it later you can run:"  ;\
-		echo "    sudo iwl-load iwlagn"  ;\
-		echo ;\
-		echo Running iwl-enable iwlwifi...;\
-		$(DESTDIR)/usr/sbin/iwl-enable iwlwifi ;\
-	fi
-	@# If on distributions like Mandriva which like to
-	@# compress their modules this will find out and do
-	@# it for you. Reason is some old version of modutils
-	@# won't know mac80211.ko should be used instead of
-	@# mac80211.ko.gz
-	@./scripts/compress_modules
-	@# Mandrake doesn't have a depmod.d/ conf file to prefer
-	@# the updates/ dir which is what we use so we add one for it
-	@# (or any other distribution that doens't have this).
-	@./scripts/check_depmod
-	@# Udev stuff needed for the new compat_firmware_class.
-	@./compat/scripts/compat_firmware_install
-	@/sbin/depmod -a
-	@echo 
-	@echo Now run:
-	@echo 
-	@echo sudo make unload to unload all: wireless, bluetooth and ethernet modules
-	@echo sudo make wlunload to unload wireless modules
-	@echo sudo make btunload to unload bluetooth modules
-	@echo
-	@echo Run sudo modprobe 'driver-name' to load your desired driver. 
-	@echo If unsure reboot.
-	@echo
-
-uninstall:
-	@# New location, matches upstream
-	@rm -rf $(KLIB)/$(KMODDIR)/compat/
-	@rm -rf $(KLIB)/$(KMODDIR)/net/mac80211/
-	@rm -rf $(KLIB)/$(KMODDIR)/net/rfkill/
-	@rm -rf $(KLIB)/$(KMODDIR)/net/wireless/
-	@rm -rf $(KLIB)/$(KMODDIR)/drivers/net/usb/
-	@rm -rf $(KLIB)/$(KMODDIR)/drivers/net/wireless/
-	@rm -rf $(KLIB)/$(KMODDIR)/drivers/staging/
-	@rm -rf $(KLIB)/$(KMODDIR)/drivers/net/atl*
-	@find $(KLIB)/$(KMODDIR)/drivers/net/ -name "alx*.ko" -o -name "atl*.ko" 2>/dev/null |xargs rm -f
-	@# Lets only remove the stuff we are sure we are providing
-	@# on the misc directory.
-	@rm -f $(KLIB)/$(KMODDIR)/drivers/misc/eeprom_93cx6.ko*
-	@rm -f $(KLIB)/$(KMODDIR)/drivers/net/b44.ko*
-	@/sbin/depmod -a
-	@echo 
-
-clean:
-	@if [ -d net -a -d $(KLIB_BUILD) ]; then \
-		$(MAKE) -C $(KLIB_BUILD) M=$(PWD) clean ;\
-	fi
-	@rm -f $(CREL_PRE)*
-unload:
-	@./scripts/unload.sh
-
-btunload:
-	@./scripts/btunload.sh
-
-wlunload:
-	@./scripts/wlunload.sh
-
-
-.PHONY: all clean install uninstall unload btunload wlunload modules bt Makefile
-
-endif
-
-clean-files += Module.symvers Module.markers modules modules.order
-clean-files += $(CREL_CHECK) $(CONFIG_CHECK) $(COMPAT_CONFIG)
